### ISSUE TITLE
[Feature] Add a payment gateway

### ISSUE THREAD

**Issue by sudhay23** [sudhay23/ShopOnline-Web-App#10]
#### Current Behavior
We don't have an actual way to checkout the products purchased

#### Desired Behavior
Add a payment gateway (or a dummy one) which simulates a proper checkout

**Comment by san-coding** [comment]
@sudhay23 lets not go for the dummy one, please integrate Razor pay payment gateway API or any other

**Comment by sudhay23** [comment]
@san-coding Sounds good

**Comment by san-coding** [comment]
sorry this issue is exclusive to maintainers

**Comment by sudhay23** [comment]
@ShyamaHarihar Thanks for evincing interest. Unfortunately, this is something that one of the maintainers can only address. Please go through one of our other open issues or feel free to open new ones. Join us on Discord from the link in Readme file
