### ISSUE TITLE
Fix the mobile/responsive view

### ISSUE THREAD

**Issue by bhaveshgoyal182** [sudhay23/ShopOnline-Web-App#116]
The website is not mobile friendly or it seems to be not an appealing one. Would love to work on this one !

![image](https://user-images.githubusercontent.com/60166991/136073772-453d42b0-3c66-4d0a-b5c1-728e34d115a0.png)
![image](https://user-images.githubusercontent.com/60166991/136073803-68e840a2-716a-4aee-843d-31ed4ee2432d.png)

**Comment by san-coding** [comment]
Go ahead
