### ISSUE TITLE
Add templates for Pull requests 

### ISSUE THREAD

**Issue by sudhay23** [sudhay23/ShopOnline-Web-App#119]
We would love to have prebuilt templates for Pull requests 

Refer [this](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template)

# TEMPLATE

This PR fixes #

**Description**

**Screenshot**

**Checks**
- [ ] I ensured that my changes are working fine locally
- [ ] I signed my commits (Optional) (Read about [Signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits))

**Comment by ashwinexe** [comment]
Hey, I can work on this

**Comment by sudhay23** [comment]
Great you can
