### ISSUE TITLE
Help us setup Github Actions (Continuous Integration / Build Checks) for this awesome repository

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#12]
#### Current Behavior
There are not automated Continuous Integration / Build  checks
#### Desired Behavior
Help us setup automated CI checks (Compile checks,Formatting checks etc) using GitHub actions

**Comment by ShlokMohanty** [comment]
@san-coding  can i take on this issue .I know cnotinuous integration through jenkins and build checks through jenkins as well as maven .So if you can assign me this task ?

**Comment by san-coding** [comment]
@ShlokMohanty  sure, we were looking for help on this issue

**Comment by ShlokMohanty** [comment]
@san-coding what is the deadline for submitting the task or should I update you like in stages ?

**Comment by san-coding** [comment]
Hey @ShlokMohanty , please take your time, no pressure, you can update me on how you're solving the issue

**Comment by ShlokMohanty** [comment]
@san-coding today i saw github actions from url: 
https://github.com/features/actions

**Comment by ShlokMohanty** [comment]
@san-coding i will be starting from tomorrow onwards i guess it works for you?

**Comment by san-coding** [comment]
Sure, take your time👍🏻

**Comment by san-coding** [comment]
@ShlokMohanty any update ?

**Comment by ShlokMohanty** [comment]
yeah on it @ShlokMohanty was performing github actions for integration yesterday was a little occupied will b ecompleting it soon but

**Comment by ShlokMohanty** [comment]
will be updating you tonight or for sure tomorrow morning ?

**Comment by san-coding** [comment]
Yeah sure, take you time, no hurry

**Comment by ShlokMohanty** [comment]
we need to do the build checks and continuous integration right ?

**Comment by san-coding** [comment]
Yes

**Comment by ShlokMohanty** [comment]
yes then going in the right path

**Comment by ShlokMohanty** [comment]
will be done soon

**Comment by ShlokMohanty** [comment]
![image](https://user-images.githubusercontent.com/59838234/135824932-849f78fb-82e1-42e8-841f-2c2e0b974bea.png)

so we have to add the continuous integration workflow for github actions for php i guess?

**Comment by san-coding** [comment]
yes I tried it , but it is throwing some build errors in composer.json

**Comment by san-coding** [comment]
do you know how to build the website and get a live link to preview the website after each commit

**Comment by ShlokMohanty** [comment]
@san-coding live preview can you explain me what is it live preview are you talking about the changes we see on the code that gets directly implemented to the server ?

**Comment by ShlokMohanty** [comment]
@san-coding should i look at the compiser.json file ?

**Comment by ShlokMohanty** [comment]
if its showing an error?

**Comment by san-coding** [comment]
> @san-coding live preview can you explain me what is it live preview are you talking about the changes we see on the code that gets directly implemented to the server ?

Yes , refer to this https://github.com/layer5io/layer5/discussions/2240

**Comment by san-coding** [comment]
> if its showing an error?

yes, try setting up php checks , it will create the `php.yml` file, which throws errors in `composer.json` in each build

**Comment by san-coding** [comment]
have to fix that

**Comment by ShlokMohanty** [comment]
@san-coding yes sure fill try to fix that

**Comment by san-coding** [comment]
@ShlokMohanty , sure , please start working on this
