### ISSUE TITLE
Add Contact us page

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#14]
#### Current Behavior
There is no contact page
#### Desired Behavior
Add `contact us` page with relevant social media and GitHub repo links, you can also automate and send out an email if a person clicks on any of the links

**Comment by rohit1kumar** [comment]
in footer?

**Comment by san-coding** [comment]
Yeah 👍🏻

**Comment by san-coding** [comment]
> in footer?

 you can add it as a footer in the landing page (`index.html`) or add a navigation link to separate `Contact us page`,

**Comment by ampsteric** [comment]
hi , i can add make a footer and add all links , please assign this issue to me @san-coding

**Comment by san-coding** [comment]
yeah sure
