### ISSUE TITLE
 Integrate Social Login in a Web API Solution

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#140]
**Current State**

Social logins buttons aren't functional

**Desired State**

Implement Backend with any Auth provider (preferably Auth0), open up child issues for each task
(Dont generate your own API keys)

- [ ] #141
- [ ] #144
- [ ] #142
- [ ] #145

### Feel free to open issues / PRs for whichever social logins you had like to integrate
Make sure the issue names are uniform - `Implement (Social-media) login authentication`
### Do not generate your own API keys (Ask for the keys, when you start working on the issue)

**Comment by san-coding** [comment]
Make sure the issue names are uniform c`Implement (Social-media) login authentication`

**Comment by JuniorS6** [comment]
@san-coding I would like to work on this

**Comment by JuniorS6** [comment]
Please assign this task to me.

**Comment by san-coding** [comment]
@JuniorS6 which task would you like to work on ?

**Comment by JuniorS6** [comment]
> @JuniorS6 which task would you like to work on ?

I would like to work on Github login auth

**Comment by san-coding** [comment]
comment on that issue
