### ISSUE TITLE
Implement Google login authentication

### ISSUE THREAD

**Issue by sudhay23** [sudhay23/ShopOnline-Web-App#141]
**Current State**
Google login buttons isn't functional

**Desired State**

Implement Backend with for the Login with Google button
" Derieved from #140 "

### Do not generate your own API keys (Ask for the keys, when you start working on the issue)

**Comment by san-coding** [comment]
Yes templates aren't working

**Comment by cyberwizard1001** [comment]
@san-coding Can I work on this?

**Comment by san-coding** [comment]
can you take this up after the GitHub login?

**Comment by cyberwizard1001** [comment]
I am planning to use Firebase login, so the steps aren't going to be that different. Will begin with Github and work my way through all of them
