### ISSUE TITLE
Subscribe us button is not functional

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#156]
**Current State**

There is a subscribe us button in the landing page UI but it doesn't redirect anywhere

**Desired State**

It should bring up a popup asking for email, and send an automatic email to the entered email

**Screenshots**

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/65719940/136698817-a3892d18-823a-473b-abb1-065641d5637f.png">
(Currently the button is not functional)

**Comment by san-coding** [comment]
Sure

**Comment by sudhay23** [comment]
![](https://cdn.optinmonster.com/wp-content/uploads/2017/09/aweber-welcome-email-best-practices-1.jpg)

Something of this sort might work


> It is! Can you elaborate a bit more on what exactly is needed? What content is to be added to the mail? If possible share an HTML markup that is to be rendered in the mail

@raj-laddha
