### ISSUE TITLE
URL of hosted project?

### ISSUE THREAD

**Issue by ankityadavhere** [sudhay23/ShopOnline-Web-App#16]

**Comment by ankityadavhere** [comment]
Hey, I'm not that familiar with PHP cuz I mostly work in Js env, Can I do the frontend part in Hacktober, as I do UI/UX designing i can create beautiful landing pages!

**Comment by san-coding** [comment]
Yeah sure, feel free to open issues to revamp the UI

**Comment by san-coding** [comment]
we are working hosting it , will hosted soon

**Comment by san-coding** [comment]
@sudhay , why have you opened a duplicate issue ?

**Comment by sudhay23** [comment]
@ankityadavhere The project is now hosted please refer issue #17 for the updates. We'll soon update how to run the app locally too.
