### ISSUE TITLE
[FRONTEND] What should be the tech stack?

### ISSUE THREAD

**Issue by ankityadavhere** [sudhay23/ShopOnline-Web-App#23]
As we're using HTML with tailwind, I don't think it'll be much scalable. So, what say @sudhay23 @san-coding 

Should we use something else?
Ps... Currently working with homepage

**Comment by sudhay23** [comment]
@ankityadavhere Yeah true that. But since this was a beginner level application, we thought of keeping it there. But we (with @san-coding) got bigger plans soon. Hope you can join us there 🎉

**Comment by ankityadavhere** [comment]
So I continue with tailwind?

**Comment by san-coding** [comment]
> Okay, Will continue doing the revamp with tailwind 👍

Sure , you can revamp with tailwind, we are looking for an attractive UI 👍🏻, thank you showing interest👍🏻
