### ISSUE TITLE
[SEO] - Perform fixes to <head> to make the website SEO friendly

### ISSUE THREAD

**Issue by ankityadavhere** [sudhay23/ShopOnline-Web-App#26]
- [ ] All necessary Meta tags
- [ ] Twitter meta
- [ ] OpenGraph tags

**Comment by ankityadavhere** [comment]
working on it.... 😴

**Comment by sudhay23** [comment]
@ankityadavhere You have it assignedd now. Good going 👍

**Comment by ankityadavhere** [comment]
PR #34 closes this
