### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by ankityadavhere** [sudhay23/ShopOnline-Web-App#28]
- [x] #51
- [ ] Login
- [ ] Admin
- [ ] Cart.... (as of now)
This is a child issue of parent issue #24

**Comment by falguni-k** [comment]
Hi! I would like to work on this issue. Please assign it to me.
Thanks!

**Comment by san-coding** [comment]
@falguni-k there are 4 tasks, which one would you like to take up ?

**Comment by AwsmNinad25** [comment]
Assign this issue to me I would like to work on the landing page

**Comment by san-coding** [comment]
@AwsmNinad25 please comment on that issue, I have opened an issue for landing page
