### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by ankityadavhere** [sudhay23/ShopOnline-Web-App#29]
- [ ] #44
- [x] #32

**Comment by san-coding** [comment]
Leave a comment on the issue if you want me to assign It to you🎉

**Comment by AwsmNinad25** [comment]
I want to work on global dark mode toggle please assign me

**Comment by Omkar845** [comment]
Can I work on this issue if no one is assigned

**Comment by Omkar845** [comment]
global dark mode toggle

**Comment by shubhrastogi07** [comment]
I would like to work on #32 issue
please assign it to me

**Comment by san-coding** [comment]
@shubhrastogi07 currently favicon is present only in the index.html page, add it to the whole web app

**Comment by san-coding** [comment]
you can open a PR for that
