### ISSUE TITLE
Add a 404 page

### ISSUE THREAD

**Issue by ankityadavhere** [sudhay23/ShopOnline-Web-App#31]
Design and create and 404 page

**Comment by san-coding** [comment]
Hey @ankityadavhere can you add the labels to issue you open ? Thanks

**Comment by ankityadavhere** [comment]
> Hey @ankityadavhere can you add the labels to issue you open ? Thanks

I don't have a option to 🤷‍♂️

**Comment by princekushwaha** [comment]
I want to work on this

**Comment by kartik633** [comment]
Can i Work on this

**Comment by san-coding** [comment]
Thank you guys for showing interest👍🏻, i have assigned this to @princekushwaha for now, since he came first

**Comment by san-coding** [comment]
@kartik633 There are plenty of other issues you can work upon, this is a project in its beginning stage, you can open more issue on revamping UI/backend and work on it🎉

**Comment by princekushwaha** [comment]
> Thank you guys for showing interest👍🏻, i have assigned this to @princekushwaha for now, since he came first

I have created the page. Take a look at it.


![404](https://user-images.githubusercontent.com/57499371/135605522-6c778f25-a7ab-441d-b41a-3eea30f6e4d6.png)

**Comment by ankityadavhere** [comment]
> > Thank you guys for showing interest👍🏻, i have assigned this to @princekushwaha for now, since he came first
> 
> I have created the page. Take a look at it.
> 
> ![404](https://user-images.githubusercontent.com/57499371/135605522-6c778f25-a7ab-441d-b41a-3eea30f6e4d6.png)

Can you add some basic animations to it?

**Comment by ankityadavhere** [comment]
@princekushwaha  Can you add some basic animation to it?

**Comment by princekushwaha** [comment]
What about 360 deg rotation of 404 gem. It will look good I guess.

**Comment by princekushwaha** [comment]
Hey I have updated it look at this.
![simplescreenrecorder-2021-10-01_17 56 58](https://user-images.githubusercontent.com/57499371/135619852-daa10585-cd5b-4f95-ab6a-6b9f09c88e44.gif)

**Comment by sudhay23** [comment]
Looks great. So how are you planning to make it functional given that this application is built using PHP?

**Comment by san-coding** [comment]
@princekushwaha , it looks amazing🎉

**Comment by san-coding** [comment]
@sudhay23 for now lets merge this , we can later figure out how to call this whenever the error occurs

**Comment by princekushwaha** [comment]
I will add .htaccess at the root and redirect the request to 404.html for a status code 404.

**Comment by princekushwaha** [comment]
> @sudhay23 for now lets merge this , we can later figure out how to call this whenever the error occurs That is a issue in itself😅

U may create another issue for this I will resolve it too 😁

**Comment by princekushwaha** [comment]
> @princekushwaha , it looks amazing🎉, just make sure the `Return to home page` button when clicked takes you to the home page, you can go ahead and create the PR , thank you for your contributions👍🏻

I already added anchor tag for home page there.

**Comment by san-coding** [comment]
Have you opened the PR for this issue ?

**Comment by princekushwaha** [comment]
I will make PR after 20min.

**Comment by princekushwaha** [comment]
I have made the PR.

**Comment by san-coding** [comment]
Thanks @princekushwaha , appreciate your efforts🎉

**Comment by san-coding** [comment]
> > @sudhay23 for now lets merge this , we can later figure out how to call this whenever the error occurs That is a issue in itself😅
> 
> U may create another issue for this I will resolve it too 😁

shall I make a PR for this
