### ISSUE TITLE
Favicon for our website

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#32]
![image](https://user-images.githubusercontent.com/65719940/135603624-ccd2a5e9-49a0-4883-9baa-670d77a31a5d.png)
Favicon is the logo that you see on the tab

**Comment by san-coding** [comment]
@kartik633 woul you like to work on this issue ?

**Comment by shreyaansjain06** [comment]
i want to work on this issue

**Comment by sudhay23** [comment]
@shreyaansjain06 Thanks for evincing interest. Yeah you can work on this

**Comment by shreyaansjain06** [comment]
Thanks for giving me this issue can you provide the image you want as favicon

**Comment by sudhay23** [comment]
You can take the 'cart' logo from our existing hosted link. But you may make some photo edits so it looks good on all title bars (even dark ones)

**Comment by shreyaansjain06** [comment]
ok i will

**Comment by shreyaansjain06** [comment]
![cart ](https://user-images.githubusercontent.com/86606251/135609944-a87d1a8c-728d-4262-98de-c45e1020981b.jpeg)


How is it this will work in all title bars i can change background colour if you want

**Comment by mayankgoyal-13** [comment]
hi, i would like to contribute to this, I can create favicons for different dimensions of laptop, android and ios. Also, I can provide you with a new logo

**Comment by shreyaansjain06** [comment]
I have made a pr you can check and if you want any more changes do let me know

**Comment by san-coding** [comment]
> ![favicon](https://user-images.githubusercontent.com/86606251/135616573-fa6b14ce-1ffc-46e1-b322-44c4d2a307df.jpeg)
> 
> How is it this will work in all title bars i can change background colour if you want

go ahead with this favicon
