### ISSUE TITLE
add a `manifest.json` and `robots.txt`

### ISSUE THREAD

**Issue by ankityadavhere** [sudhay23/ShopOnline-Web-App#33]

**Comment by ShlokMohanty** [comment]
@ankityadavhere can i work on this issue ?
can you assign me this task?

**Comment by ankityadavhere** [comment]
> @ankityadavhere can i work on this issue ? can you assign me this task?

I'm not the maintainer of this project :)

**Comment by ankityadavhere** [comment]
Hey, @ShlokMohanty are you working on this?

**Comment by ShlokMohanty** [comment]
yes i would be excited and would surely work on this

**Comment by ShlokMohanty** [comment]
just waiting to be assigned

**Comment by ankityadavhere** [comment]
PR #41 closes this
