### ISSUE TITLE
Image loading error

### ISSUE THREAD

**Issue by mayankgoyal-13** [sudhay23/ShopOnline-Web-App#36]
#### Description

The images in row 1 of browse products are not able to load on the live website. This issue can arise due to error in file format or wrong relative path.

#### Expected Behavior

All the images should be loaded properly.

#### Screenshots/Logs

![image_parth_error](https://user-images.githubusercontent.com/65842833/135614650-ea9d888b-7dcc-4672-8e79-5f751aa22738.PNG)

**Comment by mayankgoyal-13** [comment]
Hey, I would like to contribute and fix this error. Pls label it Hacktoberfest and assign it to me

**Comment by ankityadavhere** [comment]
seems like the cdn links are broken, need to change them, also the images are not high resolution 🤔 
@san-coding should I add new images?

**Comment by ankityadavhere** [comment]
PR #42 closes this issue

**Comment by san-coding** [comment]
Yes you can add new images

**Comment by san-coding** [comment]
@mayankgoyal-13 , I will be opening a new issue now, will assign it to you

**Comment by mayankgoyal-13** [comment]
okay
