### ISSUE TITLE
Sticky Navbar feature request

### ISSUE THREAD

**Issue by SayantaniDeb** [sudhay23/ShopOnline-Web-App#38]
#### Current Behavior
The navbar isnt sticky

#### Desired Behavior
The navbar will be made sticky

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by SayantaniDeb** [comment]
Please assign me this task!

**Comment by san-coding** [comment]
Welcome to shopOnline , thank you for showing interest,  feel free to reach out for help

**Comment by san-coding** [comment]
Can you show a sample screenshot of what you plan to implement , @SayantaniDeb

**Comment by san-coding** [comment]
Hey @SayantaniDeb are you working on this ?

**Comment by SayantaniDeb** [comment]
https://user-images.githubusercontent.com/74983536/135757048-a8ec07f5-cd60-4b09-bef1-9dff31f34da3.mp4

The changes made here are:
* The scrollbar UI is changed
* The navbar is made sticky in all the pages.
@san-coding

**Comment by san-coding** [comment]
Thanks @SayantaniDeb , looks amazing, you can go ahead and create the PR

**Comment by san-coding** [comment]
Hey @SayantaniDeb , unfortunately , this PR has reverted the changes made by @sudhay23 in PR #52 and #56, @sudhay23 can you please compare your and her changes to figure out we can make both work
