### ISSUE TITLE
Incorrect syntax in `shoponline.sql`

### ISSUE THREAD

**Issue by sudhay23** [sudhay23/ShopOnline-Web-App#40]
#### Description
The DB file to be imported seems to have some syntax issues and fails to get imported

#### Expected Behavior
The SQL file can be imported

**Comment by sudhay23** [comment]
@san-coding Can you help us out with this?

**Comment by san-coding** [comment]
Sure

**Comment by san-coding** [comment]
I think replacing the acute/backtick (`) with double quotes will solve the problem, will add a PR soon

**Comment by san-coding** [comment]
@sudhay23 please review this PR
