### ISSUE TITLE
Global dark mode toggle (should be based on user's system settings initially) `prefers-color-scheme`

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#44]
@AwsmNinad25 do you want to work on this ?

**Comment by san-coding** [comment]
@omkar845 shall I assign this to you

**Comment by Omkar845** [comment]
yes assign me

**Comment by san-coding** [comment]
Thank you for showing interest, looking forward to merging you contributions🎉

**Comment by san-coding** [comment]
@Omkar845 are you working on this issue ?

**Comment by Omkar845** [comment]
I made a dark mode toggle button but unable to code in JavaScript need to add some js framework

**Comment by Omkar845** [comment]
Plz help me

**Comment by san-coding** [comment]
Please open the pull request with the code you have added so far , so that I can review and help you out

**Comment by san-coding** [comment]
you can add more commits even after you have opened the PR, those commits will be reflected in that PR as long as the commits are in the same branch, feel free to reach out for any help, open the PR

**Comment by san-coding** [comment]
@Omkar845 please make a PR with whatever you have done, so that I can help you
