### ISSUE TITLE
add discord server invite link to footer in landing page , readme.md and contributions.md

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#45]
#### Current Behavior
We have a discord server but it is not added to any file
#### Desired Behavior
add discord server invite link to footer in landing page , readme.md and contributions.md

Discord invite link - https://discord.gg/yhtkaawfNq

**Comment by san-coding** [comment]
@mayankgoyal-13  or @shlokmohanty , would anyone of you like to take this up ?

**Comment by shashank1503-cipher** [comment]
Hey can i work on this issue

**Comment by san-coding** [comment]
sure @shashank1503-cipher , welcome to ShopOnline, looking forward to your contributions 🎉

**Comment by ShlokMohanty** [comment]
@san-coding  was not active when your text showed up just saw it now sorry for the delayed reply .

**Comment by san-coding** [comment]
@ShlokMohanty , its okay, shall I tag you on issue that I open? feel free to open issues. , I will assign it to you
