### ISSUE TITLE
[Docs] Add more screenshots of the UI

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#5]
**Current State:**
Some screenshots are available
**Desired State:**
Add more in the order of app workflow

**Comment by AwsmNinad25** [comment]
I would like to work on this issue

**Comment by san-coding** [comment]
Sure, welcome to `ShopOnline`, star us if you like the project

**Comment by san-coding** [comment]
I will soon get back to you on how to run the app locally

**Comment by AwsmNinad25** [comment]
Sure

**Comment by san-coding** [comment]
http://shoponline-web.000webhostapp.com/login.html
Check out this

**Comment by san-coding** [comment]
Hey @AwsmNinad25 are you working on this issue

**Comment by AwsmNinad25** [comment]
Yes I am.

**Comment by san-coding** [comment]
Awesome, take screenshots from landing page, there is issue with logging in and viewing products, we are working on it, meanwhile you can take screenshots of the landing page, registration of customer and admin, login of customer and admin and put them together with the existing screenshots in the readme, make sure all the screenshots have a 1 line description in the readme, make sure they're in the order of app workflow, thank you for showing interest, feel free to reach out for any help

**Comment by san-coding** [comment]
http://shoponline-web.000webhostapp.com/index.html
 
Landing page

**Comment by AwsmNinad25** [comment]
Thank you so much and sure I'll get back to you if I need any help

**Comment by AwsmNinad25** [comment]
I have one doubt @san-coding . What will be the src for screenshots? They are currently in my local machine

**Comment by AwsmNinad25** [comment]
#37 Please review the pull request

**Comment by san-coding** [comment]
@AwsmNinad25 always reference the issue whenever you open a PR , thank you for the contribution, looking forward to more contributions from you 👍🏻
