### ISSUE TITLE
Animate Landing Page

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#51]

**Comment by san-coding** [comment]
@AwsmNinad25 please comment here, so that I can assign this to you

**Comment by AwsmNinad25** [comment]
Assign me I would like to contribute

**Comment by san-coding** [comment]
Add some beautiful animation / use tailwind css if possible

**Comment by AwsmNinad25** [comment]
Yeah sure. Thank you for assigning me

**Comment by san-coding** [comment]
@AwsmNinad25 are you working on this ?

**Comment by AwsmNinad25** [comment]
Yeah I am but it would take some time cause some other task came in between. You can unassign me and give this task to someone else

**Comment by san-coding** [comment]
No problem , take your time, but if anyone else wants to submit a PR , they are free to do so

**Comment by AwsmNinad25** [comment]
@san-coding I'll make a by PR tommorow
