### ISSUE TITLE
[Docs] Add shield/ badges for contributors and issues count

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#53]
**Current State:**

There are no shields/badges showing contributor and issue count

**Desired State:**

Add contributor and issues count shield/ badges to readme

This is what a sample badge/shield looks like  
<img width="134" alt="image" src="https://user-images.githubusercontent.com/65719940/135673626-2c8cb3de-33f9-488b-8ec2-68f5a0cd072d.png">

They can be generated for our repo from  [shields.io](https://shields.io)

**Comment by schmelto** [comment]
I would like to work on this issue
