### ISSUE TITLE
Typo: installation_guidelines.md

### ISSUE THREAD

**Issue by AwsmNinad25** [sudhay23/ShopOnline-Web-App#58]
![Screenshot from 2021-10-02 06-40-57](https://user-images.githubusercontent.com/72618584/135699331-4102f97c-794d-4678-af64-a7657d6ed28a.png)
![Screenshot from 2021-10-02 06-41-08](https://user-images.githubusercontent.com/72618584/135699335-f8e8e3a0-7c16-4871-8a17-addd18b8f336.png)

**Comment by AwsmNinad25** [comment]
I would like to resolve this issue please assign me

**Comment by sudhay23** [comment]
@AwsmNinad25 You can proceed 👍

**Comment by san-coding** [comment]
@AwsmNinad25 where is the type ?

**Comment by sudhay23** [comment]
.... "visite" the site

> @AwsmNinad25 where is the type ?

**Comment by AwsmNinad25** [comment]
> @AwsmNinad25 where is the type ?

Also "selecte prefered" language

**Comment by san-coding** [comment]
👍🏻👍🏻
