### ISSUE TITLE
[Docs] Add link to CONTRIBUTING.md in the Readme

### ISSUE THREAD

**Issue by sudhay23** [sudhay23/ShopOnline-Web-App#59]
**Current State:**
The README file lacks a link to CONTRIBUTING.md.

**Desired State:**
The README file has a link to CONTRIBUTING.md in the appropriate place (right after Installation Guidelines).

**Comment by san-coding** [comment]
I think this issue was resolved by #47  , can be closed

**Comment by sudhay23** [comment]
Just merged? Lol

**Comment by sudhay23** [comment]
@san-coding I still don't see it there

**Comment by san-coding** [comment]
Yeah , sorry

**Comment by radiantly** [comment]
Hi, I'd like to work on this issue!

**Comment by sudhay23** [comment]
Hey @radiantly. You can go ahead 🎉

**Comment by sudhay23** [comment]
@radiantly Great job
