### ISSUE TITLE
Create .env file and add database credentials to the .env file

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#6]
#### Description
Import credentials from .env files inside all the relevant PHP files
(credentials are dbname,username,password,etc)

**Comment by Parimalisgreat** [comment]
@san-coding  I would like to take it

**Comment by san-coding** [comment]
sure @Parimalisgreat

**Comment by san-coding** [comment]
for reference :

https://github.com/san-coding/ShopOnline-Web-App/blob/2a71b75bf99a765679a0c6f27d8b0cc66db26a7e/With%20PHP/backend/addProduct.php#L12-L15

we have hardcoded these in many php files, you have to put the credentials in a single file and make the other files use it, 
we already have [databaseConnect.php](https://github.com/san-coding/ShopOnline-Web-App/blob/2a71b75bf99a765679a0c6f27d8b0cc66db26a7e/With%20PHP/backend/databaseConnect.php),
you can either create a `.env` file or make all the other files use the credentials defined inside 
[databaseConnect.php](https://github.com/san-coding/ShopOnline-Web-App/blob/2a71b75bf99a765679a0c6f27d8b0cc66db26a7e/With%20PHP/backend/databaseConnect.php),

**Comment by san-coding** [comment]
@Parimalisgreat are you working on this issue ?

**Comment by sridhar-5** [comment]
can I take this up @san-coding, if this issue is inactive? I will open a pull request today itself.

**Comment by sridhar-5** [comment]
Thanks man.
