### ISSUE TITLE
Integrate a chatbot

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#60]
#### Current Behavior
There are no chatbots on the website
#### Desired Behavior
Integrate a chatbot with a floating action button that makes the chatbot popup, you can use dialogflow API or tools of your choice

**Comment by Aashish-cyber** [comment]
assgin me.

**Comment by san-coding** [comment]
Done

**Comment by san-coding** [comment]
@Aashish-cyber are you working on this ?

**Comment by Aashish-cyber** [comment]
Yeah,, I am working on it, actually it's my first contribution to open
source so and i am making this chat bot using dialogue flow API,,

**Comment by san-coding** [comment]
Ohh alright

**Comment by san-coding** [comment]
the remote origin should be your fork of this repo
