### ISSUE TITLE
Update screenshots to match latest version of codebase

### ISSUE THREAD

**Issue by radiantly** [sudhay23/ShopOnline-Web-App#63]
Could the screenshots in the README updated?

Maybe we could leverage GitHub Actions to generate the screenshots.

**Comment by sudhay23** [comment]
@radiantly Yeah sure. Let's do it 🤟

**Comment by radiantly** [comment]
Maybe someone else can take it up :)

**Comment by sudhay23** [comment]
Cool then :) 👍

**Comment by mayankgoyal-13** [comment]
i can update the screenshot in the read me file.

**Comment by san-coding** [comment]
Sure go ahead 👍🏻

**Comment by mayankgoyal-13** [comment]
in this, I have to take a screenshot of the live website and update it in the read me file. Am I correct?

**Comment by san-coding** [comment]
yes 👍🏻, updating the landing page (`index.html`) screenshots in the readme would be enough

**Comment by san-coding** [comment]
@mayankgoyal-13 I have merged some PRss which might have made some changes in the UI, so make sure you fetch and merge main branch with your newly created branch so that you can see the latest UI and we can avoid merge conflicts

**Comment by san-coding** [comment]
@mayankgoyal-13 the screenshots are outdated , please add them ASAP

**Comment by san-coding** [comment]
@omkar645 would you like to work on this documentations issue ?

**Comment by san-coding** [comment]
@vikastiwari would like to work on this , until we fix that .env error ?

**Comment by san-coding** [comment]
@vikkastiwari would you like to work on this while we sort out that issue ? just update the landing page, and login page screenshots from  [ShopOnline](http://shoponline-web.000webhostapp.com/)

**Comment by Omkar845** [comment]
> @Omkar845 would you like to work on this documentation issue ?

Yes assign me I will work on it ??

**Comment by vikkastiwari** [comment]
> @vikkastiwari would you like to work on this while we sort out that issue ? just update the landing page, and login page screenshots from [ShopOnline](http://shoponline-web.000webhostapp.com/)

Okay

**Comment by san-coding** [comment]
Two PR ? 👀

**Comment by vikkastiwari** [comment]
You assigned I worked on it... :)

**Comment by san-coding** [comment]
I asked both of you, I had assigned this to @mayankgoyal-13 who in not responding, but its okay, I will try merging both one after the other (since both your readme changes have some differences), the second PR I choose to merge will have to solve merge conflicts, but please don't repeat this , I as maintainer don't like to choose one PR over the other 😅

**Comment by vikkastiwari** [comment]
Okay

**Comment by mayankgoyal-13** [comment]
sorry for the delay, my exams were going on

**Comment by cyberwizard1001** [comment]
Is this closed or open 👀

**Comment by san-coding** [comment]
@mayankgoyal-13 are you going to open any PR related to this ?

**Comment by sudhay23** [comment]
@cyberwizard1001 @san-coding Looks like we have some merged PRs to this already..? Are we still pending on this?

**Comment by sudhay23** [comment]
@cyberwizard1001 By the way we have a popup that comes if you visit https://shoponline-web.000webhostapp.com/ for the first time and I don't see a screenshot yet. Maybe you can help us out there with a PR if you wish. 😄
