### ISSUE TITLE
Email id format validation during signup

### ISSUE THREAD

**Issue by princeprag** [sudhay23/ShopOnline-Web-App#64]
#### Current Behavior

As of now there is no email validation and so `abc@bcom` is also taken as a valid email id. In future, if features such as email verification will be implemented, such entries will create error.

#### Desired Behavior

The format of email should be validated so as `xxx@yyy.bbb` can only be given in the email field.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by princeprag** [comment]
Working on the above under HF!!!

**Comment by sudhay23** [comment]
Hello. Are you sure that abc@bcom will work?? Since we've used Email input type on HTML, I doubt the same. Maybe you can help us out with screenshots showing the bug

**Comment by princeprag** [comment]
@sudhay23 yes, was able to do..
![Uploading Screenshot (75).png…]()

**Comment by princeprag** [comment]
Yes, @sudhay23 
![Screenshot (75)](https://user-images.githubusercontent.com/51314718/135719198-3d046140-379d-40a3-bafd-a80898c6e0c3.png)

**Comment by san-coding** [comment]
@sudhay23 , email is not validated properly, currently it checks only if `@` is present, I was going to open this issue, thanks @princeprag , I will assign this to you

**Comment by san-coding** [comment]
@princeprag are you working on this ?

**Comment by princeprag** [comment]
@san-coding Yes
