### ISSUE TITLE
center the get started button

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#67]
## Get started button is not centered (Make sure the website remains responsive after the change)
![image](https://user-images.githubusercontent.com/65719940/135759369-ada10137-e011-4ec8-804e-6b629700d89d.png)

#### Desired Behavior
Center the button and add the discord link

**Comment by Abhishek07-0302** [comment]
Hey, I would like to contribute. Kindly assign me if available.

**Comment by san-coding** [comment]
please fetch , merge and then commit your issues to avoid merge conflicts, feel free to reach out for any help

**Comment by san-coding** [comment]
@Abhishek07-0302 , discord links have been added using a separate PR, just centre the button

> please fetch , merge and then commit your issues to avoid merge conflicts, feel free to reach out for any help

**Comment by san-coding** [comment]
make sure you fetch, merge and before committing your changes

**Comment by Abhishek07-0302** [comment]
> @Abhishek07-0302 , discord links have been added using a separate PR, just centre the button
> 
> > please fetch , merge and then commit your issues to avoid merge conflicts, feel free to reach out for any help

Okay

**Comment by Abhishek07-0302** [comment]
Hey please unassign me, I don't know what mistake I am doing. So, I am not able to change it.

**Comment by sridhar-5** [comment]
I'll try giving it a go. can you assign me this issue @san-coding
