### ISSUE TITLE
[Docs] Add installation guidelines to readme

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#7]
**Current State:**
Readme doesn't contain installation guidelines/steps
**Desired State:**
Add installations steps :

- [ ]  cloning the repo
- [ ] installing php, xampp
- [ ] setting up local server

**Comment by ShlokMohanty** [comment]
@san-coding can i work on this issue?

**Comment by san-coding** [comment]
@ShlokMohanty thank you for showing interest, I will be soon creating issue , will invite you to contribute

**Comment by san-coding** [comment]
@Wolfy7 always mention the issue in your PR so that the issue gets closed when your PR is merged, thank you for your contributions 🎉
