### ISSUE TITLE
Prompt the user to give a strong password

### ISSUE THREAD

**Issue by princeprag** [sudhay23/ShopOnline-Web-App#79]
#### Current Behavior

Currently the signup form accept passwords such as `123456789` which is very weak. Google also shows a warning of potential breach of such passwords

#### Desired Behavior

Prompt the user to give a strong password, at least 1 uppercase, 1 lowercase, 1 digit , 1 speacial symbol and total length between 8-15.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by princeprag** [comment]
@san-coding

**Comment by san-coding** [comment]
Sure , go ahead and make a PR
