### ISSUE TITLE
[Docs] Add discord and MIT License badges / sheilds

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#84]
[Docs] Add discord and MIT License badges / sheilds to README.md , (contributor and issue count shields/badges are already present at the top)

**Comment by AnirbanBall** [comment]
I want to work on this

**Comment by TishaJhabak1014** [comment]
@sudhay23 Can more beginner friendly issues? Plz. Let me know.

**Comment by sudhay23** [comment]
@TishaJhabak1014 Thanks for hopping in. We'll ping you once we spot more such beginner friendly issues. @san-coding

**Comment by TishaJhabak1014** [comment]
> @TishaJhabak1014 Thanks for hopping in. We'll ping you once we spot more such beginner friendly issues. @san-coding 

Yes surely. Thanks a lot. Looking forward to contribute : )
