### ISSUE TITLE
Animate registration form, browse product and footer section 

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#86]
#### Current Behavior
Only some part of the landing page is animated

#### Desired Behavior
Animate registration form, browse product and footer section  (when scrolled down) 

you can replicate the existing animation for nav bar and other elements in the landing page

**Comment by san-coding** [comment]
@TishaJhabak1014 would you like to work on this issue ?

**Comment by TishaJhabak1014** [comment]
> @TishaJhabak1014 would you like to work on this issue ?

Yes, will like to go for it

**Comment by san-coding** [comment]
Thanks

**Comment by san-coding** [comment]
> @TishaJhabak1014 would you like to work on this issue ?
> 
> You just have to change the class attribute to get this working , refer to [this PR](https://github.com/sudhay23/ShopOnline-Web-App/pull/75#issuecomment-933004670)
> 
> fetch and merge from main before you add you commits

Refer to the files changed in this PR #75 , feel free to reach out for any help

**Comment by sridhar-5** [comment]
I would like to take this up @san-coding , @sudhay23. can someone assign this to me please?

**Comment by san-coding** [comment]
@sridhar-5 I will open up issues and assign it to you

**Comment by TishaJhabak1014** [comment]
> @TishaJhabak1014 are you working on this ?

@san-coding hey, I worked on it partly, but I am having a hard time navigating through the repository.

**Comment by san-coding** [comment]
@TishaJhabak1014 , have you figured it out ? you can refer to the changes made in #75
