### ISSUE TITLE
Subscribe us feature

### ISSUE THREAD

**Issue by I-ArchanaDash** [sudhay23/ShopOnline-Web-App#88]
#### Current Behavior

Users can't get the latest updates.
#### Desired Behavior

I want to add the subscribe-us (front end) Part for the users to get the latest updates for easy shopping.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by sudhay23** [comment]
Can you elaborate on the feature?

**Comment by I-ArchanaDash** [comment]
> Can you elaborate on the feature?
Users need to enter their mail id and press the subscribe button to get notifications related to any offers/sales/price drop etc. Presently the site doesn't offer any sort of these things . But I want to do its front-end part, so the back-end has to be done by somebody else.

**Comment by sudhay23** [comment]
Oh great. You can go ahead 👍
