### ISSUE TITLE
Revamp home page

### ISSUE THREAD

**Issue by nisha331** [sudhay23/ShopOnline-Web-App#9]
#### Current Behavior
Currently the home page looks quite boring, colorless and motionless

#### Desired Behavior
I would like to revamp the home page under hacktoberfest.

**Comment by sudhay23** [comment]
@nisha331 Hello. You can work on the same 👍 . Your PR can be made towards `new-gen` branch

**Comment by san-coding** [comment]
Hey @nisha331 , welcome to `ShopOnline`, feel free to add a PR and reach out for help whenever you want

**Comment by san-coding** [comment]
@nisha331 are you working on this ?
