### ISSUE TITLE
Create a video demonstrating the functionalities of the web app

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#95]
The app hosted on 000webhost is facing some issues with login/registration and screenshots are outdated.

Run the app locally and create a video demonstrating the functionalities of the web app [HIGH PRIORITY]

**Comment by vikkastiwari** [comment]
Assign this issue to me. I will work on it and create a video demonstrating the functionalities.

**Comment by sudhay23** [comment]
@vikkastiwari Are you able to run it locally??

**Comment by vikkastiwari** [comment]
> @vikkastiwari Are you able to run it locally??

Yes, I am setting up the project locally. Though I tried running it on a local server now going with xampp.

**Comment by san-coding** [comment]
feel free to reach out for any help 👍🏻, join our discord, link in readme

**Comment by san-coding** [comment]
Maybe he can make short videos for each functionality? @sudhay23

**Comment by san-coding** [comment]
Yes that would be awesome

**Comment by sudhay23** [comment]
That'd be really cool. You may add a suitable one 👍

**Comment by san-coding** [comment]
after that , we can merge the PR

**Comment by vikkastiwari** [comment]
> Looks awesome @vikkastiwari , you can now go ahead and create the video for admin tasks

Like how the data is stored and what changes take place when we make changes in the frontend right?

**Comment by vikkastiwari** [comment]
Actually, It's still unclear if you can put more light on it then it would be awesome.

**Comment by vikkastiwari** [comment]
Okay I will work on it.

**Comment by vikkastiwari** [comment]
Got it, Now I have to login as admin and demonstrate functionalities with respect to it. Right?

**Comment by vikkastiwari** [comment]
If it seems fine, then let me know how I can make my contribution count.

**Comment by san-coding** [comment]
Thanks @vikkastiwari you can go ahead and create the PR, for now , you can add this under the screenshots, soon we will be deleting the screenshots and have just the videos
