### ISSUE TITLE
Setup GitHub actions to deploy static website

### ISSUE THREAD

**Issue by sudhay23** [sudhay23/ShopOnline-Web-App#96]
This page should automatically be updated over the internet upon editting

**Comment by san-coding** [comment]
Sure @sudhay23

**Comment by san-coding** [comment]
[This](https://github.com/marketplace?type=&verification=&query=netlify+preview+,) might help, you'd have to have a netlify account. The easier way would be to just get a netilfy account and set up a netlify bot on your repo, it'll auto-build on each commit on every PR.

**Comment by san-coding** [comment]
no first you do ML assignment lol

**Comment by sudhay23** [comment]
@san-coding Looks like it failed lol

**Comment by san-coding** [comment]
yeah

**Comment by san-coding** [comment]
@sudhay23 website is down now

**Comment by sudhay23** [comment]
Yeah 😅

**Comment by sudhay23** [comment]
@san-coding Close this now?
