### ISSUE TITLE
Add Warning popup modal for Social Login buttons

### ISSUE THREAD

**Issue by san-coding** [sudhay23/ShopOnline-Web-App#98]
Social login buttons have been added , but they're not functional yet.

Add an attractive popup modal that says `Social logins are temporarily unavailable, please register using the registration form ` until the social logins are made functional

**Comment by akshatjain1004** [comment]
I would like to work on this issue

**Comment by Omkar845** [comment]
Can I work on this issue

**Comment by san-coding** [comment]
Since @akshatjain1004 came first i will assign it to her, @Omkar845 i will open issues and assign it to you

**Comment by san-coding** [comment]
test comment

**Comment by san-coding** [comment]
@sridhar-5 , `example` workflow is malfunctioning 👆🏻

**Comment by san-coding** [comment]
@akshatjain1004 are you working on this ?

**Comment by san-coding** [comment]
Alright
